language: node_js

services:
- docker

node_js: "12"

install: ""
script: docker build -t hawohackathon2019.azurecr.io/hackathon2019-jmb-bot:latest .

deploy:
  cleanup: false
  provider: script
  script:
  - docker login -u hawohackathon2019 -p $ACR_PASSWORD hawohackathon2019.azurecr.io
  - docker push hawohackathon2019.azurecr.io/hackathon2019-jmb-bot:latest
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
